### ISSUE TITLE
WPE function

### ISSUE THREAD

**Issue by LF9076** [srk-srinivasan/Permutation-Entropy#1]
there are some question on my project: Base on the same data, the  python code of the PE function can fully get the answer.but the WPE function give me some nan value.just like this: [0.09021252881525994, 0.03897628557989071, 0.035540059964482194, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, 0.039609172832806544,] is it the code limition or my mistake on usage? 
So thanks ~~~

**Comment by srk-srinivasan** [comment]
Can you send me the time series in order to troubleshoot?
